import test from 'node:test';
import assert from 'node:assert/strict';
import {mkdtempSync,readFileSync,unlinkSync,rmdirSync} from 'node:fs';
import path from 'node:path';
import os from 'node:os';
process.env.SCHOOL_TEST='1';
process.env.SCHOOL_DATA_DIR=mkdtempSync(path.join(os.tmpdir(),'school-portal-test-'));
const {server}=await import('./server.mjs');
await new Promise(resolve=>server.listen(0,'127.0.0.1',resolve));
const base='http://127.0.0.1:'+server.address().port;
async function request(url,method='GET',body,user,headers={}){const r=await fetch(base+url,{method,headers:{Origin:base,'Content-Type':'application/json',...(user?{Cookie:user.cookie,'X-CSRF-Token':user.csrf}:{}),...headers},...(body?{body:JSON.stringify(body)}:{})});const text=await r.text();let data;try{data=JSON.parse(text);}catch{data=text;}return {status:r.status,data,headers:r.headers};}
const credentials=JSON.parse(readFileSync(path.join(process.env.SCHOOL_DATA_DIR,'pilot-access.json'),'utf8')).accounts;
const passwordFor=username=>credentials.find(a=>a.username===username).password;
async function login(username){const r=await request('/api/login','POST',{username,password:passwordFor(username)});assert.equal(r.status,200);return {cookie:r.headers.get('set-cookie').split(';')[0],csrf:r.data.csrf};}
try{
 await test('School portal integration and authorization',async t=>{
  let p1,p2,teacher,admin,jalal,saud,rid;
  await t.test('Public visitors cannot read student data or stored files',async()=>{assert.equal((await request('/')).status,200);assert.equal((await request('/api/students')).status,401);assert.equal((await request('/api/requests')).status,401);assert.equal((await request('/data/school.json')).status,404);const catalog=await request('/api/catalog');assert.equal(catalog.status,401);assert.equal((await request('/api/books')).status,401);assert.equal((await request('/api/download/f1')).status,401);assert.equal((await request('/api/books/download/anything')).status,401);assert.equal((await request('/api/leave-requests','POST',{})).status,401);});
  await t.test('Login, HttpOnly cookies, and authentication failures',async()=>{assert.equal((await request('/api/login','POST',{username:'parent',password:'wrong'})).status,401);p1=await login('parent');p2=await login('parent2');teacher=await login('teacher');admin=await login('admin');jalal=await login('jalal');saud=await login('saud');const r=await request('/api/login','POST',{username:'parent',password:passwordFor('parent')});assert.match(r.headers.get('set-cookie'),/HttpOnly/);assert.match(r.headers.get('set-cookie'),/SameSite=Strict/);});
  await t.test('Parent isolation and teacher role restrictions',async()=>{assert.deepEqual((await request('/api/students','GET',null,p1)).data.map(x=>x.id),['s1','s2']);assert.deepEqual((await request('/api/students','GET',null,p2)).data.map(x=>x.id),['s3']);assert.equal((await request('/api/students','GET',null,teacher)).status,403);assert.equal((await request('/api/manage/students','GET',null,p1)).status,403);});
  const time=new Date(Date.now()+27*3600000).toISOString().slice(0,16);
  await t.test('Forged child, cross-origin and CSRF requests rejected',async()=>{assert.equal((await request('/api/requests','POST',{student:'s3',time,reason:'اختبار'},p1)).status,403);assert.equal((await request('/api/requests','POST',{student:'s1',time,reason:'اختبار'},p1,{'X-CSRF-Token':'bad'})).status,403);assert.equal((await request('/api/requests','POST',{student:'s1',time,reason:'اختبار'},p1,{Origin:'http://example.invalid'})).status,403);});
  await t.test('Request creation, duplicate protection and date validation',async()=>{assert.equal((await request('/api/requests','POST',{student:'s1',time:'2000-01-01T10:00',reason:'اختبار'},p1)).status,400);const r=await request('/api/requests','POST',{student:'s1',time,reason:'موعد تجريبي'},p1);assert.equal(r.status,201);rid=r.data.id;assert.equal((await request('/api/requests','POST',{student:'s1',time,reason:'اختبار'},p1)).status,409);assert.equal((await request('/api/requests','GET',null,p2)).data.length,0);});
  await t.test('Only administration and counselor can approve and record departure',async()=>{assert.equal((await request('/api/requests/'+rid,'PATCH',{status:'تمت الموافقة'},p1)).status,403);assert.equal((await request('/api/requests/'+rid,'PATCH',{status:'تمت الموافقة'},teacher)).status,403);assert.equal((await request('/api/requests/'+rid,'PATCH',{status:'تم خروج الطالب'},admin)).status,409);assert.equal((await request('/api/requests/'+rid,'PATCH',{status:'تمت الموافقة'},saud)).status,200);assert.equal((await request('/api/requests/'+rid,'PATCH',{status:'تم خروج الطالب',note:'تم التسليم تجريبيًا'},admin)).status,200);const r=(await request('/api/requests','GET',null,p1)).data[0];assert.equal(r.history.length,3);assert.ok(r.history.some(h=>h.by&&h.by.includes('سعود ضحوي العنزي')));assert.equal(r.status,'تم خروج الطالب');assert.equal((await request('/api/requests/'+rid,'PATCH',{status:'جديد'},admin)).status,409);});
  await t.test('Rejection reason required and counselor or principal can reject',async()=>{const r=await request('/api/requests','POST',{student:'s2',time,reason:'طلب تجريبي'},p1);assert.equal(r.status,201);assert.equal((await request('/api/requests/'+r.data.id,'PATCH',{status:'مرفوض'},saud)).status,400);assert.equal((await request('/api/requests/'+r.data.id,'PATCH',{status:'مرفوض',note:'الموعد غير مناسب برأي الموجه الطلابي'},saud)).status,200);const res=(await request('/api/requests','GET',null,p1)).data[0];assert.equal(res.note,'الموعد غير مناسب برأي الموجه الطلابي');assert.ok(res.history.some(h=>h.by&&h.by.includes('سعود ضحوي العنزي')));});
  await t.test('Upload, correct teacher attribution, download, ownership enforcement',async()=>{const file={title:'ملف اختبار',grade:'g4',subject:'math',teacher:'t2',kind:'أوراق عمل',filename:'sample.txt',content:Buffer.from('بيانات ملف تجريبي').toString('base64')};assert.equal((await request('/api/files','POST',file,p1)).status,403);assert.equal((await request('/api/files','POST',{...file,filename:'unsafe.html'},teacher)).status,400);const r=await request('/api/files','POST',file,teacher);assert.equal(r.status,201);const c=(await request('/api/catalog','GET',null,teacher)).data;assert.equal(c.files.find(x=>x.id===r.data.id).teacher,'t1');const downloaded=await request('/api/download/'+r.data.id,'GET',null,teacher);assert.equal(downloaded.data,'بيانات ملف تجريبي');assert.match(downloaded.headers.get('content-disposition'),/attachment/);assert.equal((await request('/api/files/f2','DELETE',{},teacher)).status,403);assert.equal((await request('/api/files/'+r.data.id,'DELETE',{},teacher)).status,200);});
  await t.test('Administration CRUD, linked record safeguards, teacher announcements',async()=>{assert.equal((await request('/api/manage/grades/g4','DELETE',{},admin)).status,409);assert.equal((await request('/api/manage/students/s1','PATCH',{name:'محمد خالد العتيبي',grade:'g4',parent:'p2'},admin)).status,409);assert.equal((await request('/api/manage/subjects','POST',{name:'مادة اختبار'},admin)).status,200);const id=(await request('/api/manage/subjects','GET',null,admin)).data.items.find(x=>x.name==='مادة اختبار').id;assert.equal((await request('/api/manage/subjects/'+id,'PATCH',{name:'مادة معدلة'},admin)).status,200);assert.equal((await request('/api/manage/subjects/'+id,'DELETE',{},admin)).status,200);assert.equal((await request('/api/announcements','POST',{title:'تنبيه اختبار',body:'نص تجريبي'},teacher)).status,201);});
  await t.test('WhatsApp request review is private, idempotent and admin-only',async()=>{const body={studentName:'طالب تجريبي اسم رباعي',parentId:'0000000000',parentPhone:'966500000000',grade:'g4',reason:'اختبار رابط المراجعة',time,requestKey:'test-whatsapp-request-key'};const created=await request('/api/leave-requests','POST',body,p1);assert.equal(created.status,201);const id=created.data.id;assert.equal((await request('/api/leave-requests','POST',body,p1)).data.id,id);assert.equal((await request('/api/requests/'+id)).status,401);assert.equal((await request('/api/requests/'+id,'GET',null,p1)).status,403);assert.equal((await request('/api/requests/'+id,'GET',null,teacher)).status,403);const detail=await request('/api/requests/'+id,'GET',null,admin);assert.equal(detail.data.parentId,'0000000000');assert.equal(detail.data.parentPhone,'966500000000');assert.equal((await request('/api/leave-requests','POST',{...body,requestKey:'missing-phone',parentPhone:''},p1)).status,400);assert.equal(detail.data.requestKey,undefined);assert.ok(!(await request('/api/requests','GET',null,p1)).data.some(r=>r.id===id));assert.equal((await request('/api/requests/'+id,'PATCH',{status:'تمت الموافقة'},p1)).status,403);assert.equal((await request('/api/requests/'+id,'PATCH',{status:'تمت الموافقة',note:'تم التحقق تجريبيًا'},admin)).status,200);assert.equal((await request('/api/requests/'+id,'GET',null,admin)).data.history.length,2);assert.equal((await request('/api/leave-requests','POST',{...body,requestKey:'another',parentId:'12'},p1)).status,400);assert.equal((await request('/api/leave-requests','POST',body,p1,{Origin:'https://example.invalid'})).status,403);});
  await t.test('Data persisted on disk and logout invalidates session',async()=>{const disk=JSON.parse(readFileSync(path.join(process.env.SCHOOL_DATA_DIR,'school.json'),'utf8'));assert.equal(disk.requests.find(x=>x.id===rid).status,'تم خروج الطالب');assert.equal((await request('/api/logout','POST',{},p1)).status,200);assert.equal((await request('/api/students','GET',null,p1)).status,401);});
  await t.test('Superadmin exclusive privileges for Mr. Jalal Al-Sultani',async()=>{
   p1=await login('parent');
   assert.equal((await request('/api/superadmin/accounts','GET',null,admin)).status,403);
   assert.equal((await request('/api/superadmin/accounts','GET',null,p1)).status,403);
   assert.equal((await request('/api/superadmin/accounts','GET',null,teacher)).status,403);
   const r=await request('/api/superadmin/accounts','GET',null,jalal);
   assert.equal(r.status,200);
   assert.ok(r.data.some(a=>a.username==='jalal'&&a.role==='superadmin'));
   const created=await request('/api/superadmin/accounts','POST',{username:'testuser',name:'مستخدم تجريبي',role:'teacher',password:'pass123'},jalal);
   assert.equal(created.status,201);
   const toggled=await request('/api/superadmin/accounts/testuser','PATCH',{action:'toggle'},jalal);
   assert.equal(toggled.status,200);
   assert.equal(toggled.data.disabled,true);
   const cannotDisableSuper=await request('/api/superadmin/accounts/jalal','PATCH',{action:'toggle'},jalal);
   assert.equal(cannotDisableSuper.status,403);
   const reset=await request('/api/superadmin/accounts/testuser','PATCH',{action:'reset'},jalal);
   assert.equal(reset.status,200);
   assert.ok(reset.data.password);
  });
 });
}finally{await new Promise(resolve=>server.close(resolve));for(const file of ['school.json','accounts.json','pilot-access.json'])unlinkSync(path.join(process.env.SCHOOL_DATA_DIR,file));rmdirSync(process.env.SCHOOL_DATA_DIR);}

